name       : haskell-setlocale
version    : 1.0.0.4
release    : 1
source     :
    - http://hackage.haskell.org/package/setlocale-1.0.0.4/setlocale-1.0.0.4.tar.gz : 32396aedcb8fdd6c56821dcde25c2cbd76462b13a6dc229bec29cb78df1fa7e9
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell bindings to setlocale
description: |
    Haskell bindings to setlocale
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
