name       : haskell-setlocale
version    : 1.0.0.6
release    : 2
source     :
    - https://hackage.haskell.org/package/setlocale-1.0.0.6/setlocale-1.0.0.6.tar.gz : 587af63153c1f3642de2c2f526b3a3c82c46ece3bd09ffd96a0eedbfd1c288e6
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell bindings to setlocale
description: |
    Haskell bindings to setlocale
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
