name       : haskell-setlocale
version    : 1.0.0.10
release    : 5
source     :
    - https://hackage.haskell.org/package/setlocale-1.0.0.10/setlocale-1.0.0.10.tar.gz : 3972ff10c22318f5451215dc886c1535fea5ab7dfefe5ce461b1603865423ba7
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell bindings to setlocale
description: |
    Haskell bindings to setlocale
builddeps  :
    - ghc-devel
setup      : |
    cp -f $pkgfiles/3.cabal setlocale.cabal
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
